### ISSUE TITLE
获取及刷新access_token报错！

### ISSUE THREAD

**Issue by huichen2017** [youzan/open-sdk-php#29]
获取及刷新access_token报错。
Fatal error: Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in D:\youzan\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:201 Stack trace: #0 D:\youzan\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\youzan\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\youzan\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 D:\youzan\vendor\guzzlehttp\ in D:\youzan\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 201

**Comment by xu42** [comment]
@huichen2017 本地证书链[存在问题](https://www.google.com/search?q=cURL+error+60%3A+SSL+certificate+problem%3A+self+signed+certificate+in+certificate+chain&oq=cURL+error+60%3A+SSL+certificate+problem%3A+self+signed+certificate+in+certificate+chain)，建议自行解决
