### ISSUE TITLE
希望加入对 guzzlehttp/guzzle 7.x 的支持

### ISSUE THREAD

**Issue by bolechen** [youzan/open-sdk-php#30]
很多框架最低要求已经是 guzzlehttp/guzzle 7.x 了，在使用这些框架的时候，用这个包会有冲突。

**Comment by xu42** [comment]
@bolechen   `guzzlehttp/guzzle` 7.x 需要要求 PHP >= 7.2
作为一个SDK，不应对PHP版本要求过高（目前要求 > 7.0），所以暂时不会去升级 `guzzlehttp/guzzle` 到 7.x

**Comment by bolechen** [comment]
不用强制要求，加一个 ^6.3 | ^7.0 就可以向下兼容了

**Comment by xu42** [comment]
> 不用强制要求，加一个 ^6.3 | ^7.0 就可以向下兼容了

如果方便的话，麻烦提一个 PR ～
