### ISSUE TITLE
2.0.0 之前的tags全部被删除了？

### ISSUE THREAD

**Issue by alberthuang24** [youzan/open-sdk-php#9]

**Comment by xu42** [comment]
@HongjiangHuang 开放平台正在迁移到有赞云。
若要使用开放平台SDK, 可按此引入: `composer require youzanyun/open-sdk "dev-carmen"`

**Comment by alberthuang24** [comment]
明白了.  希望后续删除tag 或者 其他分支时. 考虑一下影响. 譬如我们依赖某个版本时. 在新的机器上安装 `composer install` 这时候因为你们将目标tag删除而导致报错。
